#services:
#  app:
#    entrypoint:
#    - sleep
#    - infinity
#    image: docker/dev-environments-java:stable-1
#    init: true
#    volumes:
#    - type: bind
#      source: /var/run/docker.sock
#      target: /var/run/docker.sock
#


version: "3.8"
services:
  java-service:
    image: docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8090:8080
    networks:
      - springapipostgresql-net
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresqldb:5432/test
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql"
    restart: always
    ports:
      - 5433:5432
    networks:
      - springapipostgresql-net
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

networks:
  springapipostgresql-net:
